module.exports = {
  name: 'CyberChef',
  acronym: 'CHEF',
  description:
    'Attempts to decode highlighted strings with the CyberChef Magic operation.',
  onDemandOnly: true,
  defaultColor: 'light-green',
  logging: {
    level: 'info' //trace, debug, info, warn, error, fatal
  },
  entityTypes: ['*'],
  customTypes: [
    {
      key: 'encodedString',
      regex: /\S[\s\S]{2,9999}\S/
    }
  ],
  styles: ['./styles/style.less'],
  block: {
    component: {
      file: './components/block.js'
    },
    template: {
      file: './templates/block.hbs'
    }
  },
  request: {
    cert: '',
    key: '',
    passphrase: '',
    ca: '',
    proxy: ""
  },
  options: [
    {
      key: 'url',
      name: 'CyberChef Url',
      description:
        'Add your CyberChef Url to open up the CyberChef dashboard for full functionality. (e.g. https://gchq.github.io/CyberChef)',
      default: 'https://gchq.github.io/CyberChef',
      type: 'text',
      userCanEdit: false,
      adminOnly: false
    },
    {
      key: 'onlyShowMagic',
      name: 'Only Show Magic Results',
      description:
        'When checked, strings searched that do not immediately have a Magic suggestion will not be displayed in the overlay.',
      default: true,
      type: 'boolean',
      userCanEdit: true,
      adminOnly: false
    },
    {
      key: 'ignoreEntityTypes',
      name: 'Ignore Entity Types',
      description:
        'When checked, strings searched that are one of our predefined entity types ' +
        '(IPv4, IPv6, IPv4CIDR, MD5, SHA1, SHA256, MAC, string, email, domain, url, and cve) will not be displayed in the overlay.',
      default: true,
      type: 'boolean',
      userCanEdit: true,
      adminOnly: false
    },
    {
      key: 'runMagicFunctionByDefault',
      name: 'Run Magic Function By Default',
      description:
        "If checked, when you search a string by default the Magic Function's first recommended Operation will be applied to your input. " +
        'No Operation wil be applied if the Magic Function has no suggestions.',
      default: false,
      type: 'boolean',
      userCanEdit: true,
      adminOnly: false
    },
    {
      key: 'dontShowStepResults',
      name: "Don't Show Step Results",
      description:
        "By default, you can find the results for each step of your recipe when expanding on the Operation's title." +
        'If the step results are getting too long you can check this to make only the final output visible in the overlay.',
      default: false,
      type: 'boolean',
      userCanEdit: true,
      adminOnly: false
    },
    {
      key: 'minLength',
      name: 'Minimum Input Length',
      description: 'The minimum text input length for a string to be considered Input.',
      default: 5,
      type: 'number',
      userCanEdit: true,
      adminOnly: false
    },
    {
      key: 'favourites',
      name: 'Favourite Operations',
      description:
        'This is a list of the Favourites that will show up when you initially search for operations.',
      default: [
        { value: 'To Base64', display: 'To Base64' },
        { value: 'From Base64', display: 'From Base64' },
        { value: 'To Hex', display: 'To Hex' },
        { value: 'From Hex', display: 'From Hex' },
        { value: 'To Hexdump', display: 'To Hexdump' },
        { value: 'From Hexdump', display: 'From Hexdump' },
        { value: 'URL Decode', display: 'URL Decode' },
        { value: 'Entropy', display: 'Entropy' }
      ],
      type: 'select',
      options: [
        { value: 'To Base64', display: 'To Base64' },
        { value: 'From Base64', display: 'From Base64' },
        { value: 'To Hex', display: 'To Hex' },
        { value: 'From Hex', display: 'From Hex' },
        { value: 'To Hexdump', display: 'To Hexdump' },
        { value: 'From Hexdump', display: 'From Hexdump' },
        { value: 'URL Decode', display: 'URL Decode' },
        { value: 'Entropy', display: 'Entropy' },
        { value: 'MD2', display: 'MD2' },
        { value: 'A1Z26 Cipher Decode', display: 'A1Z26 Cipher Decode' },
        { value: 'ADD', display: 'ADD' },
        { value: 'AND', display: 'AND' },
        { value: 'Add line numbers', display: 'Add line numbers' },
        { value: 'Add Text To Image', display: 'Add Text To Image' },
        { value: 'Adler-32 Checksum', display: 'Adler-32 Checksum' },
        { value: 'Affine Cipher Decode', display: 'Affine Cipher Decode' },
        { value: 'Affine Cipher Encode', display: 'Affine Cipher Encode' },
        { value: 'Analyse hash', display: 'Analyse hash' },
        { value: 'Atbash Cipher', display: 'Atbash Cipher' },
        { value: 'Avro to JSON', display: 'Avro to JSON' },
        { value: 'BLAKE2b', display: 'BLAKE2b' },
        { value: 'BLAKE2s', display: 'BLAKE2s' },
        { value: 'BSON deserialise', display: 'BSON deserialise' },
        { value: 'BSON serialise', display: 'BSON serialise' },
        { value: 'Bacon Cipher Decode', display: 'Bacon Cipher Decode' },
        { value: 'Bacon Cipher Encode', display: 'Bacon Cipher Encode' },
        { value: 'Bcrypt', display: 'Bcrypt' },
        { value: 'Bcrypt compare', display: 'Bcrypt compare' },
        { value: 'Bcrypt parse', display: 'Bcrypt parse' },
        { value: 'Bifid Cipher Decode', display: 'Bifid Cipher Decode' },
        { value: 'Bifid Cipher Encode', display: 'Bifid Cipher Encode' },
        { value: 'Bit shift left', display: 'Bit shift left' },
        { value: 'Bit shift right', display: 'Bit shift right' },
        { value: 'Blowfish Decrypt', display: 'Blowfish Decrypt' },
        { value: 'Blowfish Encrypt', display: 'Blowfish Encrypt' },
        { value: 'Blur Image', display: 'Blur Image' },
        { value: 'Bzip2 Compress', display: 'Bzip2 Compress' },
        { value: 'Bzip2 Decompress', display: 'Bzip2 Decompress' },
        { value: 'CRC-16 Checksum', display: 'CRC-16 Checksum' },
        { value: 'CRC-32 Checksum', display: 'CRC-32 Checksum' },
        { value: 'CRC-8 Checksum', display: 'CRC-8 Checksum' },
        { value: 'CSS Beautify', display: 'CSS Beautify' },
        { value: 'CSS Minify', display: 'CSS Minify' },
        { value: 'CSS selector', display: 'CSS selector' },
        { value: 'CSV to JSON', display: 'CSV to JSON' },
        { value: 'CTPH', display: 'CTPH' },
        { value: 'Cartesian Product', display: 'Cartesian Product' },
        { value: 'Change IP format', display: 'Change IP format' },
        { value: 'Chi Square', display: 'Chi Square' },
        { value: 'CipherSaber2 Decrypt', display: 'CipherSaber2 Decrypt' },
        { value: 'CipherSaber2 Encrypt', display: 'CipherSaber2 Encrypt' },
        { value: 'Citrix CTX1 Decode', display: 'Citrix CTX1 Decode' },
        { value: 'Citrix CTX1 Encode', display: 'Citrix CTX1 Encode' },
        { value: 'Compare CTPH hashes', display: 'Compare CTPH hashes' },
        { value: 'Compare SSDEEP hashes', display: 'Compare SSDEEP hashes' },
        { value: 'Contain Image', display: 'Contain Image' },
        { value: 'Convert area', display: 'Convert area' },
        { value: 'Convert co-ordinate format', display: 'Convert co-ordinate format' },
        { value: 'Convert data units', display: 'Convert data units' },
        { value: 'Convert distance', display: 'Convert distance' },
        { value: 'Convert Image Format', display: 'Convert Image Format' },
        { value: 'Convert mass', display: 'Convert mass' },
        { value: 'Convert speed', display: 'Convert speed' },
        { value: 'Convert to NATO alphabet', display: 'Convert to NATO alphabet' },
        { value: 'Count occurrences', display: 'Count occurrences' },
        { value: 'Cover Image', display: 'Cover Image' },
        { value: 'Crop Image', display: 'Crop Image' },
        { value: 'DES Decrypt', display: 'DES Decrypt' },
        { value: 'DES Encrypt', display: 'DES Encrypt' },
        { value: 'DNS over HTTPS', display: 'DNS over HTTPS' },
        { value: 'Dechunk HTTP response', display: 'Dechunk HTTP response' },
        { value: 'Decode NetBIOS Name', display: 'Decode NetBIOS Name' },
        { value: 'Decode text', display: 'Decode text' },
        { value: 'Defang IP Addresses', display: 'Defang IP Addresses' },
        { value: 'Defang URL', display: 'Defang URL' },
        { value: 'Derive EVP key', display: 'Derive EVP key' },
        { value: 'Derive PBKDF2 key', display: 'Derive PBKDF2 key' },
        { value: 'Detect File Type', display: 'Detect File Type' },
        { value: 'Diff', display: 'Diff' },
        { value: 'Disassemble x86', display: 'Disassemble x86' },
        { value: 'Dither Image', display: 'Dither Image' },
        { value: 'Divide', display: 'Divide' },
        { value: 'Drop bytes', display: 'Drop bytes' },
        { value: 'Encode NetBIOS Name', display: 'Encode NetBIOS Name' },
        { value: 'Encode text', display: 'Encode text' },
        { value: 'Escape string', display: 'Escape string' },
        { value: 'Escape Unicode Characters', display: 'Escape Unicode Characters' },
        { value: 'Expand alphabet range', display: 'Expand alphabet range' },
        { value: 'Extract dates', display: 'Extract dates' },
        { value: 'Extract domains', display: 'Extract domains' },
        { value: 'Extract EXIF', display: 'Extract EXIF' },
        { value: 'Extract email addresses', display: 'Extract email addresses' },
        { value: 'Extract file paths', display: 'Extract file paths' },
        { value: 'Extract Files', display: 'Extract Files' },
        { value: 'Extract IP addresses', display: 'Extract IP addresses' },
        { value: 'Extract LSB', display: 'Extract LSB' },
        { value: 'Extract MAC addresses', display: 'Extract MAC addresses' },
        { value: 'Extract RGBA', display: 'Extract RGBA' },
        { value: 'Extract URLs', display: 'Extract URLs' },
        { value: 'Filter', display: 'Filter' },
        { value: 'Find / Replace', display: 'Find / Replace' },
        { value: 'Fletcher-16 Checksum', display: 'Fletcher-16 Checksum' },
        { value: 'Fletcher-32 Checksum', display: 'Fletcher-32 Checksum' },
        { value: 'Fletcher-64 Checksum', display: 'Fletcher-64 Checksum' },
        { value: 'Fletcher-8 Checksum', display: 'Fletcher-8 Checksum' },
        { value: 'Flip Image', display: 'Flip Image' },
        { value: 'Format MAC addresses', display: 'Format MAC addresses' },
        { value: 'Frequency distribution', display: 'Frequency distribution' },
        { value: 'From BCD', display: 'From BCD' },
        { value: 'From Base', display: 'From Base' },
        { value: 'From Base32', display: 'From Base32' },
        { value: 'From Base58', display: 'From Base58' },
        { value: 'From Base62', display: 'From Base62' },
        { value: 'From Base85', display: 'From Base85' },
        { value: 'From Binary', display: 'From Binary' },
        { value: 'From Braille', display: 'From Braille' },
        { value: 'From Case Insensitive Regex', display: 'From Case Insensitive Regex' },
        { value: 'From Charcode', display: 'From Charcode' },
        { value: 'From Decimal', display: 'From Decimal' },
        { value: 'From HTML Entity', display: 'From HTML Entity' },
        { value: 'From Hex Content', display: 'From Hex Content' },
        { value: 'From MessagePack', display: 'From MessagePack' },
        { value: 'From Morse Code', display: 'From Morse Code' },
        { value: 'From Octal', display: 'From Octal' },
        { value: 'From Punycode', display: 'From Punycode' },
        { value: 'From Quoted Printable', display: 'From Quoted Printable' },
        { value: 'From UNIX Timestamp', display: 'From UNIX Timestamp' },
        { value: 'GOST hash', display: 'GOST hash' },
        { value: 'Generate all hashes', display: 'Generate all hashes' },
        { value: 'Generate HOTP', display: 'Generate HOTP' },
        { value: 'Generate Image', display: 'Generate Image' },
        { value: 'Generate Lorem Ipsum', display: 'Generate Lorem Ipsum' },
        { value: 'Generate PGP Key Pair', display: 'Generate PGP Key Pair' },
        { value: 'Generate QR Code', display: 'Generate QR Code' },
        { value: 'Generate RSA Key Pair', display: 'Generate RSA Key Pair' },
        { value: 'Generate TOTP', display: 'Generate TOTP' },
        { value: 'Generate UUID', display: 'Generate UUID' },
        { value: 'Generic Code Beautify', display: 'Generic Code Beautify' },
        { value: 'Group IP addresses', display: 'Group IP addresses' },
        { value: 'Gunzip', display: 'Gunzip' },
        { value: 'Gzip', display: 'Gzip' },
        { value: 'HAS-160', display: 'HAS-160' },
        { value: 'HMAC', display: 'HMAC' },
        { value: 'HTML To Text', display: 'HTML To Text' },
        { value: 'HTTP request', display: 'HTTP request' },
        { value: 'Hamming Distance', display: 'Hamming Distance' },
        { value: 'Haversine distance', display: 'Haversine distance' },
        { value: 'Head', display: 'Head' },
        { value: 'Heatmap chart', display: 'Heatmap chart' },
        { value: 'Hex Density chart', display: 'Hex Density chart' },
        { value: 'Hex to Object Identifier', display: 'Hex to Object Identifier' },
        { value: 'Hex to PEM', display: 'Hex to PEM' },
        { value: 'Image Brightness / Contrast', display: 'Image Brightness / Contrast' },
        { value: 'Image Filter', display: 'Image Filter' },
        {
          value: 'Image Hue/Saturation/Lightness',
          display: 'Image Hue/Saturation/Lightness'
        },
        { value: 'Image Opacity', display: 'Image Opacity' },
        { value: 'Index of Coincidence', display: 'Index of Coincidence' },
        { value: 'Invert Image', display: 'Invert Image' },
        { value: 'JPath expression', display: 'JPath expression' },
        { value: 'JSON Beautify', display: 'JSON Beautify' },
        { value: 'JSON Minify', display: 'JSON Minify' },
        { value: 'JSON to CSV', display: 'JSON to CSV' },
        { value: 'JWT Decode', display: 'JWT Decode' },
        { value: 'JWT Sign', display: 'JWT Sign' },
        { value: 'JWT Verify', display: 'JWT Verify' },
        { value: 'JavaScript Beautify', display: 'JavaScript Beautify' },
        { value: 'JavaScript Minify', display: 'JavaScript Minify' },
        { value: 'JavaScript Parser', display: 'JavaScript Parser' },
        { value: 'Keccak', display: 'Keccak' },
        { value: 'Luhn Checksum', display: 'Luhn Checksum' },
        { value: 'A1Z26 Cipher Encode', display: 'A1Z26 Cipher Encode' },
        { value: 'MD4', display: 'MD4' },
        { value: 'MD5', display: 'MD5' },
        { value: 'MD6', display: 'MD6' },
        { value: 'Mean', display: 'Mean' },
        { value: 'Median', display: 'Median' },
        { value: 'Microsoft Script Decoder', display: 'Microsoft Script Decoder' },
        { value: 'Multiply', display: 'Multiply' },
        { value: 'NOT', display: 'NOT' },
        { value: 'Normalise Image', display: 'Normalise Image' },
        { value: 'Normalise Unicode', display: 'Normalise Unicode' },
        { value: 'Numberwang', display: 'Numberwang' },
        { value: 'OR', display: 'OR' },
        { value: 'Object Identifier to Hex', display: 'Object Identifier to Hex' },
        { value: 'Offset checker', display: 'Offset checker' },
        {
          value: 'Optical Character Recognition',
          display: 'Optical Character Recognition'
        },
        { value: 'PEM to Hex', display: 'PEM to Hex' },
        { value: 'PGP Decrypt', display: 'PGP Decrypt' },
        { value: 'PGP Decrypt and Verify', display: 'PGP Decrypt and Verify' },
        { value: 'PGP Encrypt', display: 'PGP Encrypt' },
        { value: 'PGP Encrypt and Sign', display: 'PGP Encrypt and Sign' },
        { value: 'PGP Verify', display: 'PGP Verify' },
        { value: 'PHP Deserialize', display: 'PHP Deserialize' },
        { value: 'Pad lines', display: 'Pad lines' },
        { value: 'Parse ASN.1 hex string', display: 'Parse ASN.1 hex string' },
        { value: 'Parse colour code', display: 'Parse colour code' },
        { value: 'Parse IP range', display: 'Parse IP range' },
        { value: 'Parse IPv4 header', display: 'Parse IPv4 header' },
        { value: 'Parse IPv6 address', display: 'Parse IPv6 address' },
        { value: 'Parse ObjectID timestamp', display: 'Parse ObjectID timestamp' },
        { value: 'Parse QR Code', display: 'Parse QR Code' },
        { value: 'Parse SSH Host Key', display: 'Parse SSH Host Key' },
        { value: 'Parse TLV', display: 'Parse TLV' },
        { value: 'Parse UDP', display: 'Parse UDP' },
        { value: 'Parse UNIX file permissions', display: 'Parse UNIX file permissions' },
        { value: 'Parse URI', display: 'Parse URI' },
        { value: 'Parse User Agent', display: 'Parse User Agent' },
        { value: 'Parse X.509 certificate', display: 'Parse X.509 certificate' },
        { value: 'Play Media', display: 'Play Media' },
        { value: 'Power Set', display: 'Power Set' },
        { value: 'Protobuf Decode', display: 'Protobuf Decode' },
        {
          value: 'Pseudo-Random Number Generator',
          display: 'Pseudo-Random Number Generator'
        },
        { value: 'RC2 Decrypt', display: 'RC2 Decrypt' },
        { value: 'RC2 Encrypt', display: 'RC2 Encrypt' },
        { value: 'RC4', display: 'RC4' },
        { value: 'RC4 Drop', display: 'RC4 Drop' },
        { value: 'RIPEMD', display: 'RIPEMD' },
        { value: 'ROT13', display: 'ROT13' },
        { value: 'ROT47', display: 'ROT47' },
        { value: 'RSA Sign', display: 'RSA Sign' },
        { value: 'RSA Verify', display: 'RSA Verify' },
        { value: 'Rail Fence Cipher Decode', display: 'Rail Fence Cipher Decode' },
        { value: 'Rail Fence Cipher Encode', display: 'Rail Fence Cipher Encode' },
        { value: 'Randomize Colour Palette', display: 'Randomize Colour Palette' },
        { value: 'Raw Deflate', display: 'Raw Deflate' },
        { value: 'Raw Inflate', display: 'Raw Inflate' },
        { value: 'Remove Diacritics', display: 'Remove Diacritics' },
        { value: 'Remove EXIF', display: 'Remove EXIF' },
        { value: 'Remove line numbers', display: 'Remove line numbers' },
        { value: 'Remove null bytes', display: 'Remove null bytes' },
        { value: 'Remove whitespace', display: 'Remove whitespace' },
        { value: 'Render Image', display: 'Render Image' },
        { value: 'Render Markdown', display: 'Render Markdown' },
        { value: 'Resize Image', display: 'Resize Image' },
        { value: 'Reverse', display: 'Reverse' },
        { value: 'Rotate Image', display: 'Rotate Image' },
        { value: 'Rotate left', display: 'Rotate left' },
        { value: 'Rotate right', display: 'Rotate right' },
        { value: 'SHA0', display: 'SHA0' },
        { value: 'SHA1', display: 'SHA1' },
        { value: 'SHA3', display: 'SHA3' },
        { value: 'SM3', display: 'SM3' },
        { value: 'SQL Beautify', display: 'SQL Beautify' },
        { value: 'SQL Minify', display: 'SQL Minify' },
        { value: 'SSDEEP', display: 'SSDEEP' },
        { value: 'SUB', display: 'SUB' },
        { value: 'Scan for Embedded Files', display: 'Scan for Embedded Files' },
        { value: 'Scatter chart', display: 'Scatter chart' },
        { value: 'Scrypt', display: 'Scrypt' },
        { value: 'Series chart', display: 'Series chart' },
        { value: 'Set Difference', display: 'Set Difference' },
        { value: 'Set Intersection', display: 'Set Intersection' },
        { value: 'Set Union', display: 'Set Union' },
        { value: 'Shake', display: 'Shake' },
        { value: 'Sharpen Image', display: 'Sharpen Image' },
        { value: 'Show Base64 offsets', display: 'Show Base64 offsets' },
        { value: 'Show on map', display: 'Show on map' },
        { value: 'Sleep', display: 'Sleep' },
        { value: 'Snefru', display: 'Snefru' },
        { value: 'Sort', display: 'Sort' },
        { value: 'Split', display: 'Split' },
        { value: 'Split Colour Channels', display: 'Split Colour Channels' },
        { value: 'Standard Deviation', display: 'Standard Deviation' },
        { value: 'Streebog', display: 'Streebog' },
        { value: 'Strings', display: 'Strings' },
        { value: 'Strip HTML tags', display: 'Strip HTML tags' },
        { value: 'Strip HTTP headers', display: 'Strip HTTP headers' },
        { value: 'Substitute', display: 'Substitute' },
        { value: 'Subtract', display: 'Subtract' },
        { value: 'Sum', display: 'Sum' },
        { value: 'Swap endianness', display: 'Swap endianness' },
        { value: 'Symmetric Difference', display: 'Symmetric Difference' },
        { value: 'Syntax highlighter', display: 'Syntax highlighter' },
        { value: 'TCP/IP Checksum', display: 'TCP/IP Checksum' },
        { value: 'Tail', display: 'Tail' },
        { value: 'Take bytes', display: 'Take bytes' },
        { value: 'Text Encoding Brute Force', display: 'Text Encoding Brute Force' },
        { value: 'To BCD', display: 'To BCD' },
        { value: 'To Base', display: 'To Base' },
        { value: 'To Base32', display: 'To Base32' },
        { value: 'To Base58', display: 'To Base58' },
        { value: 'To Base62', display: 'To Base62' },
        { value: 'To Base85', display: 'To Base85' },
        { value: 'To Binary', display: 'To Binary' },
        { value: 'To Braille', display: 'To Braille' },
        { value: 'To Camel case', display: 'To Camel case' },
        { value: 'To Case Insensitive Regex', display: 'To Case Insensitive Regex' },
        { value: 'To Charcode', display: 'To Charcode' },
        { value: 'To Decimal', display: 'To Decimal' },
        { value: 'To HTML Entity', display: 'To HTML Entity' },
        { value: 'To Hex Content', display: 'To Hex Content' },
        { value: 'To Kebab case', display: 'To Kebab case' },
        { value: 'To Lower case', display: 'To Lower case' },
        { value: 'To MessagePack', display: 'To MessagePack' },
        { value: 'To Morse Code', display: 'To Morse Code' },
        { value: 'To Octal', display: 'To Octal' },
        { value: 'To Punycode', display: 'To Punycode' },
        { value: 'To Quoted Printable', display: 'To Quoted Printable' },
        { value: 'To Snake case', display: 'To Snake case' },
        { value: 'To Table', display: 'To Table' },
        { value: 'To UNIX Timestamp', display: 'To UNIX Timestamp' },
        { value: 'To Upper case', display: 'To Upper case' },
        { value: 'Triple DES Decrypt', display: 'Triple DES Decrypt' },
        { value: 'Triple DES Encrypt', display: 'Triple DES Encrypt' },
        { value: 'Typex', display: 'Typex' },
        {
          value: 'UNIX Timestamp to Windows Filetime',
          display: 'UNIX Timestamp to Windows Filetime'
        },
        { value: 'URL Encode', display: 'URL Encode' },
        { value: 'Unescape string', display: 'Unescape string' },
        { value: 'Unescape Unicode Characters', display: 'Unescape Unicode Characters' },
        { value: 'Unicode Text Format', display: 'Unicode Text Format' },
        { value: 'Unique', display: 'Unique' },
        { value: 'Untar', display: 'Untar' },
        { value: 'Unzip', display: 'Unzip' },
        { value: 'VarInt Decode', display: 'VarInt Decode' },
        { value: 'VarInt Encode', display: 'VarInt Encode' },
        { value: 'View Bit Plane', display: 'View Bit Plane' },
        { value: 'Vigenère Decode', display: 'Vigenère Decode' },
        { value: 'Vigenère Encode', display: 'Vigenère Encode' },
        { value: 'Whirlpool', display: 'Whirlpool' },
        {
          value: 'Windows Filetime to UNIX Timestamp',
          display: 'Windows Filetime to UNIX Timestamp'
        },
        { value: 'XKCD Random Number', display: 'XKCD Random Number' },
        { value: 'XML Beautify', display: 'XML Beautify' },
        { value: 'XML Minify', display: 'XML Minify' },
        { value: 'XOR', display: 'XOR' },
        { value: 'XOR Brute Force', display: 'XOR Brute Force' },
        { value: 'XPath expression', display: 'XPath expression' },
        { value: 'YARA Rules', display: 'YARA Rules' },
        { value: 'Zlib Deflate', display: 'Zlib Deflate' },
        { value: 'Zlib Inflate', display: 'Zlib Inflate' }
      ],
      multiple: true,
      userCanEdit: true,
      adminOnly: false
    }
  ]
};
